darajati/darajati/urls.py
from django.urls import re_path, include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = i18n_patterns(
    path('login/', views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('admin/', admin.site.urls),
    re_path(r'^impersonate/', include('impersonate.urls')),
    path('logout/', views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
)

urlpatterns += i18n_patterns(
    # Enrollment
    re_path(r'', include('enrollment.urls', namespace='enrollment')),
    re_path(r'attendance/', include('attendance.urls', namespace='attendance')),
    re_path(r'grade/', include('grade.urls', namespace='grade')),
    re_path(r'banner-integration/', include('banner_integration.urls', namespace='banner_integration')),

    # Exams
    re_path(r'exam/', include('exam.urls', namespace='exam')),
)

urlpatterns += [
    path('explorer/', include('explorer.urls')),
    path('session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

darajati/enrollment/urls.py
from django.urls import re_path
from django.views.generic import TemplateView

from . import views

app_name = 'enrollment'

# Instructor
urlpatterns = [
    re_path(r'^$', views.HomeView.as_view(), name='home'),
    re_path(r'^instructor/$', views.InstructorView.as_view(), name='instructor'),
    re_path(r'^student/section/(?P<section_id>[0-9]+)/$', views.SectionStudentView.as_view(),
        name='section_students'),
]

# Coordinator
urlpatterns += [
    re_path(r'^coordinator/$', views.CoordinatorView.as_view(), name='coordinator'),
    re_path(r'^coordinator/course/(?P<course_offering_id>[0-9]+)/$', views.CoordinatorSectionView.as_view(),
            name='course_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/$',
            views.CoordinatorGradeFragmentView.as_view(),
            name='grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/import-fragments/$',
            views.ImportGradeFragmentsView.as_view(), name='import_fragments'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/bulk-update/$',
            views.BulkUpdateGradeFragmentsView.as_view(), name='bulk_update'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/edit/(?P<pk>[0-9]+)/$',
            views.CoordinatorEditGradeFragmentView.as_view(),
            name='update_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/delete/(?P<pk>[0-9]+)/$',
            views.CoordinatorDeleteGradeFragmentView.as_view(),
            name='delete_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/create/$',
            views.CoordinatorCreateGradeFragmentView.as_view(),
            name='create_grade_fragment_coordinator'),
    re_path(r'^coordinator/section/(?P<section_id>[0-9]+)/$', views.CoordinatorView.as_view(),
            name='section_coordinator'),
    re_path(r'^coordinator/grades/(?P<course_offering_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/import-grade/$',
            views.ImportGradesView.as_view(), name='import_grade'),
]

# Admin
urlpatterns += [
    re_path(r'^controls/$', views.AdminControlsView.as_view(), name='controls'),
]

# Others
urlpatterns += [
    re_path(r'^unauthorized/$', TemplateView.as_view(template_name='unauthorized.html'), name='unauthorized'),
]

darajati/exam/urls.py
from django.urls import re_path

from . import views

app_name = 'exam'

urlpatterns = [
    re_path(r'^rooms/$',
            views.RoomListView.as_view(),
            name='list_rooms'
            ),

    re_path(r'^rooms/add/$',
            views.RoomAddView.as_view(),
            name='add_room'
            ),

    re_path(r'^rooms/(?P<room_id>[0-9]+)/edit/$',
            views.RoomEditView.as_view(),
            name='edit_room'
            ),

    re_path(r'^settings/(?P<fragment_id>[0-9]+)/$',
            views.ExamSettingsView.as_view(),
            name='settings'
            ),

    re_path(r'^shifts/(?P<fragment_id>[0-9]+)/$',
            views.ExamShiftsView.as_view(),
            name='shifts'
            ),

    re_path(r'^rooms/(?P<fragment_id>[0-9]+)/$',
            views.ExamRoomsView.as_view(),
            name='exam_rooms'
            ),

    re_path(r'^markers/(?P<fragment_id>[0-9]+)/$',
            views.MarkersView.as_view(),
            name='markers'
            ),

    re_path(r'^marks/(?P<marker_id>[0-9]+)/$',
            views.StudentMarksView.as_view(),
            name='marks'
            ),

    re_path(r'^unaccepted/(?P<fragment_id>[0-9]+)/$',
            views.UnacceptedStudentMarksView.as_view(),
            name='unaccepted_markers'
            ),

    re_path(r'^markers-listing/(?P<fragment_id>[0-9]+)/$',
            views.CoordinatorMarkersListing.as_view(),
            name='coordinator_markers_listing'
            ),
]

darajati/grade/urls.py
from . import views
from django.urls import re_path, path

app_name = 'grade'

urlpatterns = [
    re_path(r'^section/(?P<section_id>[0-9]+)/$',
            views.GradeFragmentView.as_view(),
            name='section_grade'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/$',
            views.GradesView.as_view(),
            name='plan_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/view/$',
            views.DisplayGradesView.as_view(),
            name='view_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/create-grade-plan/$',
            views.CreateGradeFragmentView.as_view(),
            name='create_grade_fragment'),

    re_path(r'^section/(?P<section_id>[0-9]+)/grades-report/$',
            views.GradeReportView.as_view(),
            name='section_grade_report'),

    re_path(r'^letter-grades/(?P<course_offering_id>[0-9]+)/$',
            views.LetterGradesView.as_view(), name='letter_grades'),

    path('letter-grades-promotion/<int:course_offering_id>/', views.LetterGradesPromotionView.as_view(),
         name='letter_grades_promotion'),

    path('letter-grades/<int:course_offering_id>/import/', views.ImportLetterGradesView.as_view(),
         name='letter_grades_import'),

    path('missing-grades-report/<int:course_offering_id>/', views.MissingGradesReportView.as_view(),
         name='missing_grades_report'),
]

darajati/grade/models.py
from decimal import *

from django.conf import settings
from django.db import models
from django.db import transaction
from django.db.models import Sum, Count
from django.db.models import Value
from django.db.models.functions import Concat
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from simple_history.models import HistoricalRecords

from darajati.utils import decimal
from enrollment.utils import to_string, now, today

User = settings.AUTH_USER_MODEL


class GradeFragment(models.Model):
    class GradesBoundaries:
        OBJECTIVE = 'OBJECTIVE'
        SUBJECTIVE_BOUNDED = 'SUBJECTIVE_BOUNDED'
        SUBJECTIVE_BOUNDED_FIXED = 'SUBJECTIVE_BOUNDED_FIXED'
        SUBJECTIVE_FREE = 'SUBJECTIVE_FREE'
        SUBJECTIVE_MARKING = 'SUBJECTIVE_MARKING'

        @classmethod
        def choices(cls):
            return (
                (cls.OBJECTIVE, _('Objective')),
                (cls.SUBJECTIVE_BOUNDED, _('Subjective bound')),
                (cls.SUBJECTIVE_BOUNDED_FIXED, _('Subjective bound Fixed')),
                (cls.SUBJECTIVE_FREE, _('Subjective Free')),
                (cls.SUBJECTIVE_MARKING, _('Subjective Marking')),
            )

    course_offering = models.ForeignKey(
        'enrollment.CourseOffering',
        on_delete=models.CASCADE,
        related_name="grade_fragments",
        null=True,
        blank=False
    )
    section = models.ForeignKey(
        'enrollment.Section',
        on_delete=models.CASCADE,
        related_name="GradeFragment",
        null=True,
        blank=True)
    category = models.CharField(
        _('Category'),
        max_length=100,
        null=True,
        blank=False,
        help_text='Categories are like: Quiz, Midterm, Final Exam etc..'
    )
    description = models.CharField(
        _('Description'), max_length=100,
        null=True,
        blank=False
    )
    weight = models.DecimalField(
        _('Weight'),
        null=True,
        blank=False,
        default=0.0,
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    entry_start_date = models.DateTimeField(
        _('Allowed entry start date'),
        null=True,
        blank=False,
        help_text=_('Set the entry date and time to allow instructor to enter grades')
    )
    entry_end_date = models.DateTimeField(
        _('Allowed entry end date'),
        null=True,
        blank=False,
        help_text=_('Set the entry date and time to allow instructor to enter grades')
    )
    order = models.PositiveSmallIntegerField(
        _('Display Order'),
        null=True,
        blank=False,
        help_text=_('The order of which grade break down should show up first')
    )
    show_teacher_report = models.BooleanField(
        _('Show in Teacher Report'),
        null=False,
        blank=False,
        default=True,
        help_text=_('This flag will control whether teachers are be able to see grades of this fragment '
                    'in darajati or in BI')
    )
    show_student_report = models.BooleanField(
        _('Show in Student Report'),
        null=False,
        blank=False,
        default=True
    )
    boundary_type = models.CharField(
        _('Boundary Type'), max_length=24,
        choices=GradesBoundaries.choices(),
        null=True,
        blank=False,
        default=GradesBoundaries.SUBJECTIVE_FREE)
    boundary_range_upper = models.DecimalField(
        _('Boundary Range Upper'), null=True, blank=True,
        help_text=_(
            'When the type is subjective and it is not free, give a positive range'),
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    boundary_range_lower = models.DecimalField(
        _('Boundary Range Lower'),
        null=True,
        blank=True,
        help_text=_('When the type is subjective and it is not free, give a negative range'),
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    boundary_fixed_average = models.DecimalField(
        _('Boundary Fixed Average'),
        null=True,
        blank=True,
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    allow_change = models.BooleanField(
        _('Allow Change After Submission'),
        null=False,
        blank=False,
        default=True
    )
    student_total_grading = models.BooleanField(
        _('Calculate In Student Grading?'),
        default=False,
        help_text=_('If this is checked, It will be calculated in the total mark')
    )
    entry_in_percentages = models.BooleanField(
        _('Entry in Percentages'),
        null=False,
        blank=True,
        default=False,
        help_text=_('Checked when the course entered grades are in %')
    )
    grade_promotion_criterion = models.BooleanField(
        _('Letter Grade Promotion Criterion?'),
        blank=False,
        default=0,
        help_text=_('This if checked indicates the criterion for which coordinators can promote final letter grades '
                    'for students who performed in it better than their letter grade. There should be only one '
                    'fragment for the whole course offering that can be flagged as the criterion.')
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='updated_grade_fragments',
        null=True,
        blank=True
    )
    updated_on = models.DateTimeField(
        _('Updated On'),
        auto_now=True,
        null=True,
    )

    class Meta:
        ordering = ['order']

    def __str__(self):
        return to_string(self.course_offering, self.category, self.description)

    @staticmethod
    def get_grade_fragment(grade_fragment_id):
        """
        :param grade_fragment_id: an integer number 
        :return: a GradeFragment instance if exists else None
        """
        return get_object_or_404(GradeFragment, pk=grade_fragment_id)

    @staticmethod
    def get_section_grade_fragments(section):
        """
        :param section: a section instance 
        :return: list of grade fragments instances of a section or if the section is coordinated return 
        a list of that coordinated course
        """
        if section.course_offering.coordinated:
            return GradeFragment.objects.filter(course_offering=section.course_offering)
        return GradeFragment.objects.filter(section=section.id)

    @staticmethod
    def get_all_fragments_choices():
        # FIXME: to only return grade fragments of the current active semesters.
        """
        :return: dic of id and value of all grade fragments. 
        """
        return GradeFragment.objects.all().annotate(
            value=Concat(
                'course_offering__course__code',
                Value(' '), 'description',
                output_field=models.CharField()
            )
        ).values_list('id', 'value')

    def get_fragment_boundary(self, section):
        """
        :param section: 
        :return: a string to present the boundary of subjective fragment 
        """
        boundary_range_lower = self.boundary_range_lower or 0
        boundary_range_upper = self.boundary_range_upper or 0
        boundary_fixed_average = self.boundary_fixed_average or 0

        if self.boundary_type == self.GradesBoundaries.SUBJECTIVE_BOUNDED:
            average = StudentGrade.get_section_objective_average(
                section,
                self
            )
            if average:
                lower = average - boundary_range_lower
                upper = average + boundary_range_upper
                if self.entry_in_percentages:
                    return 'This section average should be between ' + str(lower) + '% and ' + str(upper) + '%'
                return 'This section average should be between ' + str(lower) + ' and ' + str(upper)
        if self.boundary_type == self.GradesBoundaries.SUBJECTIVE_BOUNDED_FIXED:
            lower = boundary_fixed_average - boundary_range_lower
            upper = boundary_fixed_average + boundary_range_upper
            if self.entry_in_percentages:
                return 'This section average should be between ' + str(lower) + '% and ' + str(upper) + '%'
            return 'This section average should be between ' + str(lower) + ' and ' + str(upper)

    def is_entry_allowed_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is  trying to access a grade fragment grades within the allowed time
        """
        try:
            entry_allowed = self.entry_start_date <= now() <= self.entry_end_date
            if not entry_allowed:
                return section.is_coordinator_section(instructor)
            return entry_allowed
        except GradeFragment.DoesNotExist:
            pass

    def is_change_allowed_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is a coordinator or allow_change is enabled in the fragment
        """
        try:
            if not self.allow_change:
                return section.is_coordinator_section(instructor)
            return self.allow_change
        except GradeFragment.DoesNotExist:
            pass

    def is_viewable_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is able to see the fragment grades in reports
        """
        if not self.show_teacher_report:
            return section.is_coordinator_section(instructor)
        return self.show_teacher_report

    @property
    def allow_subjective_marking(self):
        """
        :return: True if boundary_type is SUBJECTIVE_MARKING
        """
        return self.boundary_type == self.GradesBoundaries.SUBJECTIVE_MARKING

    def get_section_average(self, section):
        return StudentGrade.get_section_average(
            section, self
        )

    @property

darajati/grade/templates/grade/create_grade_fragment.html
{% extends "base.html" %}
{% load i18n staticfiles %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>

{% endblock %}

darajati/grade/templates/grade/grade_break_down.html
{% extends "base.html" %}
{% load i18n staticfiles %}
{% block content %}
<div class="content-panel">
    <div class="cntnt-sec">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li
                    {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if grades_break_down %}
        <h3>{% trans 'Welcome, find your current enrolled sections grades break down' %}</h3>
        <br>
        {% with grades_break_down|first as item %}
            <span><strong>{% trans 'Course : ' %}</strong>{{ item.course.name }}</span>
            <br>
            {% if item.section %}<span><strong>{% trans 'Section : ' %}</strong>{{ item.section.code }}</span>{% endif %}
        {% endwith %}

        <table class="table table-condensed text-center">
            <thead>
            <tr>
                <th class="text-center">{% trans 'Category' %}</th>
                <th class="text-center">{% trans 'Description' %}</th>
                <th class="text-center">{% trans 'Weight' %}</th>
                <th class="text-center">{% trans 'Type' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for grade_break_down in grades_break_down %}
            <tr>
                <td>{{ grade_break_down.category }}</td>
                <td>{{ grade_break_down.description }}</td>
                <td>{{ grade_break_down.weight }}</td>
                <td>{{ grade_break_down.boundary_type }}</td>
                <td><a href="{% url 'grade:plan_grades' section_id=section_id  grade_break_down_id=grade_break_down.id%}"
                       class="thm-btn small-btn outline-btn-dgrey">{% trans 'View/Edit' %}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        {% trans 'There are no results' %}
        {% endif %}

    </div>
</div>
{% endblock %}

darajati/grade/templates/grade/grade_fragments.html
{% extends "base.html" %}
{% load i18n staticfiles %}
{% block content %}
	<div class="content-panel">
		<div class="cntnt-sec">
			<div class="back-btn"><a href="{% url 'enrollment:home' %}">{% trans 'Go Back' %}</a></div>
			<div class="title-sec text-center">
				<h3>{% trans 'Course:' %} {{ section.course_offering.course.name }}</h3>
				<p>{% trans 'Find your current enrolled sections grades plans' %}</p>
			</div>
			{% if not section.course_offering.coordinated %}
				<div class="float-right">
					<a class="thm-btn small-btn outline-btn-dgrey"
					   href="{% url 'grade:create_grade_fragment' section_id=section_id %}">
						{% trans 'Create New Grade Plan' %}</a>
				</div>
			{% endif %}
			{#            <div class="float-right">#}
			{#                <a class="thm-btn small-btn outline-btn-dgrey"#}
			{#                   href="{% url 'grade:section_grade_report' section_id=section_id %}">#}
			{#                    {% trans 'Grades Report' %}</a>#}
			{#            </div>#}
		</div>

		{% if grade_fragments_objects %}
			<table class="table table-condensed text-center">
				<thead>
				<tr>
					<th class="text-center">{% trans 'No.' %}</th>
					<th class="text-center">{% trans 'Category' %}</th>
					<th class="text-center">{% trans 'Description' %}</th>
					<th class="text-center">{% trans 'Weight' %}</th>
					<th class="text-center">{% trans 'Entry Date' %}</th>
					<th class="text-center">{% trans 'Type' %}</th>
					<th class="text-center">{% trans 'Grades' %}</th>
				</tr>
				</thead>
				<tbody>
				{% for object in grade_fragments_objects %}
					<tr>
						<td>{{ object.grade_fragment.order }}</td>
						<td>{{ object.grade_fragment.category }}</td>
						<td>{{ object.grade_fragment.description }}</td>
						<td>{{ object.grade_fragment.weight }}</td>
						<td{% if object.editable %} class="warning"{% endif %}>{{ object.grade_fragment.entry_start_date }} to {{ object.grade_fragment.entry_end_date }}</td>
						<td>{{ object.grade_fragment.get_boundary_type_display }}</td>
						{% if object.editable %}
							<td>
								<a href="{% url 'grade:plan_grades' section_id=section_id  grade_fragment_id=object.grade_fragment.id %}"
								   class="thm-btn small-btn outline-btn-dgrey btn-success">{% trans 'Edit' %}</a></td>
						{% elif object.viewable %}
							<td>
								<a href="{% url 'grade:view_grades' section_id=section_id  grade_fragment_id=object.grade_fragment.id %}"
								   class="thm-btn small-btn outline-btn-dgrey">{% trans 'View' %}</a></td>
						{% endif %}
					</tr>
				{% endfor %}
				</tbody>
			</table>
		{% else %}
			<br>
			<h4>
				{% trans 'There are no results' %}
			</h4>
		{% endif %}

	</div>
{% endblock %}

darajati/grade/templates/grade/letter_grades.html
{% extends "base.html" %}
{% load i18n staticfiles humanize %}

{% block content %}
	<div class="content-panel">
		<br>
		<div class="cntnt-sec">
			<div class="title-sec text-center">
				<h3>{% trans 'Letter Grades' %}</h3><br>
				<h4>{% trans "Overall GPA" %}: <b>{{ overall_gpa|floatformat:4 }}</b></h4>
			</div>
			<div class="card card-outline-secondary mb-3">
				<div class="card-block">
					<blockquote class="card-blockquote">
						<p>{% trans 'Semester: ' %}<span>{{ course_offering.semester.description }}</span></p>
						<p>{% trans 'Course: ' %}<span>{{ course_offering.course }}</span></p>
						<p>{% trans 'Coordinated: ' %}<span>{{ course_offering.coordinated }}</span>
						</p>
					</blockquote>
				</div>
			</div>
			{% if formset.forms %}
				<form method="post">
					<div class="title-sec row">
						<div class="col-md-offset-1 col-md-11 text-right">
							{% if can_import_fragments %}
							<a class="small-btn thm-btn" href="{% url 'grade:letter_grades_import' course_offering.pk %}">
								<span class="glyphicon glyphicon-import"></span> {% trans 'Import From Previous Semester' %}</a>
							{% endif %}
							{% if letter_grade_promotion_enabled %}
							<a href="{% url 'grade:letter_grades_promotion' course_offering_id=course_offering.id %}"
							   class="small-btn thm-btn">
								<span class="glyphicon glyphicon-cloud-upload" aria-hidden="true"></span> {% trans 'Letter Grades Promotion' %}
							</a>
							{% endif %}
							<button class="small-btn thm-btn" type="submit" name="save">
								<span class="glyphicon glyphicon-save-file"></span> {% trans 'Save' %}</button>
							<button class="small-btn thm-btn" type="submit" name="csv"
							        onclick="return confirm('{% trans "Are you sure?" %}');">
								<span class="glyphicon glyphicon-th"></span> {% trans 'Export To CSV' %}</button>
							<button class="small-btn thm-btn" type="submit" name="apply"
							        onclick="return confirm('{% trans "Are you sure?" %}');">
								<span class="glyphicon glyphicon-saved"></span> {% trans 'Save and Apply' %}</button>
						</div>
					</div>
					<br>
					<div class="thm-table odd period-cntnt">
						<table class="table">
							<thead>
							<tr>
								<th>{% trans 'No.' %}</th>
								<th>{% trans 'Letter Grade' %}</th>
								<th>{% trans 'Cut-Off Point' %}</th>
								<th>{% trans 'No Of Students' %}</th>
								<th>{% trans 'Updated By' %}</th>
								<th>{% trans 'Updated On' %}</th>
								<th>{% trans 'Delete?' %}</th>
							</tr>
							</thead>
							<tbody>
							{% csrf_token %}
							{{ formset.management_form }}
							{% for form in formset %}
								<tr>
									<td>
										<div class="row">
											<div class="col-md-12">
												{{ form.id }}{{ forloop.counter }}{{ form.non_field_errors }}
											</div>
										</div>
									</td>
									<td>
										<div class="row">
											<div class="col-md-12">
												{{ form.letter_grade }}{{ form.letter_grade.errors }}</div>
										</div>
									</td>
									<td>
										<div class="row">
											<div class="col-md-12">
												{{ form.cut_off_point }}{{ form.cut_off_point.errors }}</div>
										</div>
									</td>
									<td>{% for letter_grade in letter_grades_counts %}
										{% if letter_grade.calculated_letter_grade == form.instance.letter_grade %}
											{{ letter_grade.entries }}{% endif %}{% endfor %}</td>
									<td>{{ form.instance.updated_on|naturaltime }}</td>
									<td>{{ form.instance.updated_by }}</td>
									<td>{{ form.DELETE }}</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</form>
			{% else %}
				{% trans 'There are no letter grades yet' %}
			{% endif %}
		</div>
	</div>
{% endblock %}

darajati/grade/templates/grade/view_grades.html
{% extends "base.html" %}
{% load i18n staticfiles %}
{% block content %}
    <div class="content-panel">
        <br>
        <div class="card card-outline-secondary mb-3">
            <div class="card-block">
                <blockquote class="card-blockquote">
                    <p>{% trans 'Semester: ' %}<span>{{ grade_fragment.course_offering.semester.description }}</span></p>
                    <p>{% trans 'Course: ' %}<span>{{ grade_fragment.course_offering.course }}</span></p>
                    <p>{% trans 'Grade Fragment Category: ' %}<span>{{ grade_fragment.category }}</span></p>
                    <p>{% trans 'Grade Fragment Description: ' %}<span>{{ grade_fragment.description }}</span></p>
                    <p>{% trans 'Grade Fragment Weight: ' %}<span>{{ grade_fragment.weight }}</span></p>
                    <p>{% trans 'Grade Fragment Type: ' %}<span>{{ grade_fragment.get_boundary_type_display }}</span></p>
                    {% if boundary %}
                        <span><strong>{{ boundary }}</strong></span>
                    {% endif %}
                </blockquote>
            </div>
        </div>
        <div class="cntnt-sec">
            {% if grades %}
                <div class="title-sec row">
                    <div class="col-md-12">
                        <h3>{% trans 'Available Grades' %}</h3>
                        <span style="margin-right: 5%">{% trans 'Section Average:' %} <span
                                class="section_average">{{ section_average }}</span></span>
                    </div>
                </div>
                <table class="table table-condensed text-center">
                    <thead>
                    <tr>
                        <th class="text-center">{% trans 'No.' %}</th>
                        <th class="text-center">{% trans 'Student ID' %}</th>
                        <th class="text-center">{% trans 'Student Name' %}</th>
                        <th class="text-center">{% trans 'Mark' %}</th>
                        <th class="text-center">{% trans 'Remark' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for grade in grades %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ grade.enrollment.student.university_id }}</td>
                            <td>{{ grade.enrollment.student.english_name }}</td>
                            <td>{{ grade.display_percent_grade }}</td>
                            <td>{{ grade.remarks }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {% trans 'There are no students' %}
            {% endif %}
        </div>
    </div>
{% endblock %}