darajati/darajati/urls.py
from django.urls import re_path, include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = i18n_patterns(
    path('login/', views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('admin/', admin.site.urls),
    re_path(r'^impersonate/', include('impersonate.urls')),
    path('logout/', views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
)

urlpatterns += i18n_patterns(
    # Enrollment
    re_path(r'', include('enrollment.urls', namespace='enrollment')),
    re_path(r'attendance/', include('attendance.urls', namespace='attendance')),
    re_path(r'grade/', include('grade.urls', namespace='grade')),
    re_path(r'banner-integration/', include('banner_integration.urls', namespace='banner_integration')),

    # Exams
    re_path(r'exam/', include('exam.urls', namespace='exam')),
)

urlpatterns += [
    path('explorer/', include('explorer.urls')),
    path('session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

darajati/enrollment/urls.py
from django.urls import re_path
from django.views.generic import TemplateView

from . import views

app_name = 'enrollment'

# Instructor
urlpatterns = [
    re_path(r'^$', views.HomeView.as_view(), name='home'),
    re_path(r'^instructor/$', views.InstructorView.as_view(), name='instructor'),
    re_path(r'^student/section/(?P<section_id>[0-9]+)/$', views.SectionStudentView.as_view(),
        name='section_students'),
]

# Coordinator
urlpatterns += [
    re_path(r'^coordinator/$', views.CoordinatorView.as_view(), name='coordinator'),
    re_path(r'^coordinator/course/(?P<course_offering_id>[0-9]+)/$', views.CoordinatorSectionView.as_view(),
            name='course_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/$',
            views.CoordinatorGradeFragmentView.as_view(),
            name='grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/import-fragments/$',
            views.ImportGradeFragmentsView.as_view(), name='import_fragments'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/bulk-update/$',
            views.BulkUpdateGradeFragmentsView.as_view(), name='bulk_update'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/edit/(?P<pk>[0-9]+)/$',
            views.CoordinatorEditGradeFragmentView.as_view(),
            name='update_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/delete/(?P<pk>[0-9]+)/$',
            views.CoordinatorDeleteGradeFragmentView.as_view(),
            name='delete_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/create/$',
            views.CoordinatorCreateGradeFragmentView.as_view(),
            name='create_grade_fragment_coordinator'),
    re_path(r'^coordinator/section/(?P<section_id>[0-9]+)/$', views.CoordinatorView.as_view(),
            name='section_coordinator'),
    re_path(r'^coordinator/grades/(?P<course_offering_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/import-grade/$',
            views.ImportGradesView.as_view(), name='import_grade'),
]

# Admin
urlpatterns += [
    re_path(r'^controls/$', views.AdminControlsView.as_view(), name='controls'),
]

# Others
urlpatterns += [
    re_path(r'^unauthorized/$', TemplateView.as_view(template_name='unauthorized.html'), name='unauthorized'),
]

darajati/exam/urls.py
from django.urls import re_path

from . import views

app_name = 'exam'

urlpatterns = [
    re_path(r'^rooms/$',
            views.RoomListView.as_view(),
            name='list_rooms'
            ),

    re_path(r'^rooms/add/$',
            views.RoomAddView.as_view(),
            name='add_room'
            ),

    re_path(r'^rooms/(?P<room_id>[0-9]+)/edit/$',
            views.RoomEditView.as_view(),
            name='edit_room'
            ),

    re_path(r'^settings/(?P<fragment_id>[0-9]+)/$',
            views.ExamSettingsView.as_view(),
            name='settings'
            ),

    re_path(r'^shifts/(?P<fragment_id>[0-9]+)/$',
            views.ExamShiftsView.as_view(),
            name='shifts'
            ),

    re_path(r'^rooms/(?P<fragment_id>[0-9]+)/$',
            views.ExamRoomsView.as_view(),
            name='exam_rooms'
            ),

    re_path(r'^markers/(?P<fragment_id>[0-9]+)/$',
            views.MarkersView.as_view(),
            name='markers'
            ),

    re_path(r'^marks/(?P<marker_id>[0-9]+)/$',
            views.StudentMarksView.as_view(),
            name='marks'
            ),

    re_path(r'^unaccepted/(?P<fragment_id>[0-9]+)/$',
            views.UnacceptedStudentMarksView.as_view(),
            name='unaccepted_markers'
            ),

    re_path(r'^markers-listing/(?P<fragment_id>[0-9]+)/$',
            views.CoordinatorMarkersListing.as_view(),
            name='coordinator_markers_listing'
            ),
]

darajati/grade/urls.py
from . import views
from django.urls import re_path, path

app_name = 'grade'

urlpatterns = [
    re_path(r'^section/(?P<section_id>[0-9]+)/$',
            views.GradeFragmentView.as_view(),
            name='section_grade'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/$',
            views.GradesView.as_view(),
            name='plan_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/view/$',
            views.DisplayGradesView.as_view(),
            name='view_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/create-grade-plan/$',
            views.CreateGradeFragmentView.as_view(),
            name='create_grade_fragment'),

    re_path(r'^section/(?P<section_id>[0-9]+)/grades-report/$',
            views.GradeReportView.as_view(),
            name='section_grade_report'),

    re_path(r'^letter-grades/(?P<course_offering_id>[0-9]+)/$',
            views.LetterGradesView.as_view(), name='letter_grades'),

    path('letter-grades-promotion/<int:course_offering_id>/', views.LetterGradesPromotionView.as_view(),
         name='letter_grades_promotion'),

    path('letter-grades/<int:course_offering_id>/import/', views.ImportLetterGradesView.as_view(),
         name='letter_grades_import'),

    path('missing-grades-report/<int:course_offering_id>/', views.MissingGradesReportView.as_view(),
         name='missing_grades_report'),
]

darajati/grade/models.py
from decimal import *

from django.conf import settings
from django.db import models
from django.db import transaction
from django.db.models import Sum, Count
from django.db.models import Value
from django.db.models.functions import Concat
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from simple_history.models import HistoricalRecords

from darajati.utils import decimal
from enrollment.utils import to_string, now, today

User = settings.AUTH_USER_MODEL


class GradeFragment(models.Model):
    class GradesBoundaries:
        OBJECTIVE = 'OBJECTIVE'
        SUBJECTIVE_BOUNDED = 'SUBJECTIVE_BOUNDED'
        SUBJECTIVE_BOUNDED_FIXED = 'SUBJECTIVE_BOUNDED_FIXED'
        SUBJECTIVE_FREE = 'SUBJECTIVE_FREE'
        SUBJECTIVE_MARKING = 'SUBJECTIVE_MARKING'

        @classmethod
        def choices(cls):
            return (
                (cls.OBJECTIVE, _('Objective')),
                (cls.SUBJECTIVE_BOUNDED, _('Subjective bound')),
                (cls.SUBJECTIVE_BOUNDED_FIXED, _('Subjective bound Fixed')),
                (cls.SUBJECTIVE_FREE, _('Subjective Free')),
                (cls.SUBJECTIVE_MARKING, _('Subjective Marking')),
            )

    course_offering = models.ForeignKey(
        'enrollment.CourseOffering',
        on_delete=models.CASCADE,
        related_name="grade_fragments",
        null=True,
        blank=False
    )
    section = models.ForeignKey(
        'enrollment.Section',
        on_delete=models.CASCADE,
        related_name="GradeFragment",
        null=True,
        blank=True)
    category = models.CharField(
        _('Category'),
        max_length=100,
        null=True,
        blank=False,
        help_text='Categories are like: Quiz, Midterm, Final Exam etc..'
    )
    description = models.CharField(
        _('Description'), max_length=100,
        null=True,
        blank=False
    )
    weight = models.DecimalField(
        _('Weight'),
        null=True,
        blank=False,
        default=0.0,
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    entry_start_date = models.DateTimeField(
        _('Allowed entry start date'),
        null=True,
        blank=False,
        help_text=_('Set the entry date and time to allow instructor to enter grades')
    )
    entry_end_date = models.DateTimeField(
        _('Allowed entry end date'),
        null=True,
        blank=False,
        help_text=_('Set the entry date and time to allow instructor to enter grades')
    )
    order = models.PositiveSmallIntegerField(
        _('Display Order'),
        null=True,
        blank=False,
        help_text=_('The order of which grade break down should show up first')
    )
    show_teacher_report = models.BooleanField(
        _('Show in Teacher Report'),
        null=False,
        blank=False,
        default=True,
        help_text=_('This flag will control whether teachers are be able to see grades of this fragment '
                    'in darajati or in BI')
    )
    show_student_report = models.BooleanField(
        _('Show in Student Report'),
        null=False,
        blank=False,
        default=True
    )
    boundary_type = models.CharField(
        _('Boundary Type'), max_length=24,
        choices=GradesBoundaries.choices(),
        null=True,
        blank=False,
        default=GradesBoundaries.SUBJECTIVE_FREE)
    boundary_range_upper = models.DecimalField(
        _('Boundary Range Upper'), null=True, blank=True,
        help_text=_(
            'When the type is subjective and it is not free, give a positive range'),
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    boundary_range_lower = models.DecimalField(
        _('Boundary Range Lower'),
        null=True,
        blank=True,
        help_text=_('When the type is subjective and it is not free, give a negative range'),
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    boundary_fixed_average = models.DecimalField(
        _('Boundary Fixed Average'),
        null=True,
        blank=True,
        max_digits=settings.MAX_DIGITS,
        decimal_places=settings.MAX_DECIMAL_POINT
    )
    allow_change = models.BooleanField(
        _('Allow Change After Submission'),
        null=False,
        blank=False,
        default=True
    )
    student_total_grading = models.BooleanField(
        _('Calculate In Student Grading?'),
        default=False,
        help_text=_('If this is checked, It will be calculated in the total mark')
    )
    entry_in_percentages = models.BooleanField(
        _('Entry in Percentages'),
        null=False,
        blank=True,
        default=False,
        help_text=_('Checked when the course entered grades are in %')
    )
    grade_promotion_criterion = models.BooleanField(
        _('Letter Grade Promotion Criterion?'),
        blank=False,
        default=0,
        help_text=_('This if checked indicates the criterion for which coordinators can promote final letter grades '
                    'for students who performed in it better than their letter grade. There should be only one '
                    'fragment for the whole course offering that can be flagged as the criterion.')
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='updated_grade_fragments',
        null=True,
        blank=True
    )
    updated_on = models.DateTimeField(
        _('Updated On'),
        auto_now=True,
        null=True,
    )

    class Meta:
        ordering = ['order']

    def __str__(self):
        return to_string(self.course_offering, self.category, self.description)

    @staticmethod
    def get_grade_fragment(grade_fragment_id):
        """
        :param grade_fragment_id: an integer number 
        :return: a GradeFragment instance if exists else None
        """
        return get_object_or_404(GradeFragment, pk=grade_fragment_id)

    @staticmethod
    def get_section_grade_fragments(section):
        """
        :param section: a section instance 
        :return: list of grade fragments instances of a section or if the section is coordinated return 
        a list of that coordinated course
        """
        if section.course_offering.coordinated:
            return GradeFragment.objects.filter(course_offering=section.course_offering)
        return GradeFragment.objects.filter(section=section.id)

    @staticmethod
    def get_all_fragments_choices():
        # FIXME: to only return grade fragments of the current active semesters.
        """
        :return: dic of id and value of all grade fragments. 
        """
        return GradeFragment.objects.all().annotate(
            value=Concat(
                'course_offering__course__code',
                Value(' '), 'description',
                output_field=models.CharField()
            )
        ).values_list('id', 'value')

    def get_fragment_boundary(self, section):
        """
        :param section: 
        :return: a string to present the boundary of subjective fragment 
        """
        boundary_range_lower = self.boundary_range_lower or 0
        boundary_range_upper = self.boundary_range_upper or 0
        boundary_fixed_average = self.boundary_fixed_average or 0

        if self.boundary_type == self.GradesBoundaries.SUBJECTIVE_BOUNDED:
            average = StudentGrade.get_section_objective_average(
                section,
                self
            )
            if average:
                lower = average - boundary_range_lower
                upper = average + boundary_range_upper
                if self.entry_in_percentages:
                    return 'This section average should be between ' + str(lower) + '% and ' + str(upper) + '%'
                return 'This section average should be between ' + str(lower) + ' and ' + str(upper)
        if self.boundary_type == self.GradesBoundaries.SUBJECTIVE_BOUNDED_FIXED:
            lower = boundary_fixed_average - boundary_range_lower
            upper = boundary_fixed_average + boundary_range_upper
            if self.entry_in_percentages:
                return 'This section average should be between ' + str(lower) + '% and ' + str(upper) + '%'
            return 'This section average should be between ' + str(lower) + ' and ' + str(upper)

    def is_entry_allowed_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is  trying to access a grade fragment grades within the allowed time
        """
        try:
            entry_allowed = self.entry_start_date <= now() <= self.entry_end_date
            if not entry_allowed:
                return section.is_coordinator_section(instructor)
            return entry_allowed
        except GradeFragment.DoesNotExist:
            pass

    def is_change_allowed_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is a coordinator or allow_change is enabled in the fragment
        """
        try:
            if not self.allow_change:
                return section.is_coordinator_section(instructor)
            return self.allow_change
        except GradeFragment.DoesNotExist:
            pass

    def is_viewable_for_instructor(self, section, instructor):
        """
        :return: True if the teacher is able to see the fragment grades in reports
        """
        if not self.show_teacher_report:
            return section.is_coordinator_section(instructor)
        return self.show_teacher_report

    @property
    def allow_subjective_marking(self):
        """
        :return: True if boundary_type is SUBJECTIVE_MARKING
        """
        return self.boundary_type == self.GradesBoundaries.SUBJECTIVE_MARKING

    def get_section_average(self, section):
        return StudentGrade.get_section_average(
            section, self
        )

    @property

darajati/enrollment/forms.py
# from django import forms
# from django.utils.translation import ugettext_lazy as _
#
#
# class GradesImportForm(forms.Form):
#     def __init__(self, *args, **kwargs):
#         super(GradesImportForm, self).__init__(*args, **kwargs)
#         self.fields['grade'] = forms.CharField(
#             widget=forms.Textarea(
#                 attrs={'placeholder': _(u'Please follow the format:\n\n'
#                                         u'student_id  mark  remark\n\n'
#                                         u'0000000000 9 -1 for not writing the name')})
#         )
#         self.fields['commit'] = forms.BooleanField(
#             label=_('Commit changes'),
#             required=False,
#             help_text=_('This checkbox is for you to save the changes you viewed in the report.')
#         )

darajati/enrollment/templates/enrollment/coordinator/courses_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="content-panel">
    <div class="cntnt-sec">
        <div class="title-sec text-center">
            <h3>{% trans 'Find your current coordinated courses' %}</h3>
        </div>
        <hr>
        {% if courses %}
        <table class="table table-condensed text-center">
            <thead>
            <tr>
                <th class="text-center">{% trans 'Semester Code' %}</th>
                <th class="text-center">{% trans 'Course Code' %}</th>
                <th class="text-center">{% trans 'Course Name' %}</th>
                <th class="text-center">{% trans 'Sections' %}</th>
                <th class="text-center">{% trans 'Grade Fragments' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_offering.semester.code }}</td>
                    <td {% if course.course_offering.coordinated %} style="color:red" {% endif %}>
                        {{ course.course_offering.course.code }}</td>
                    <td>{{ course.course_offering.course.name }}</td>
                    <td><a href="{% url 'enrollment:course_coordinator' course_offering_id=course.course_offering.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'View' %}</a></td>
                    <td><a href="{% url 'enrollment:grade_fragment_coordinator' course_offering_id=course.course_offering.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'View' %}</a></td>
                </tr>
             {% endfor %}
            </tbody>
        </table>
        {% else %}
                {% trans 'There are no results' %}
        {% endif %}

    </div>
</div>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator/create_grade_fragment.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="content-panel">
        <div class="cntnt-sec">
            <div class="back-btn"> <a href="{% url 'enrollment:grade_fragment_coordinator' course_offering_id=course_offering.id %}">{% trans 'Go Back' %}</a></div>
            <div class="title-sec text-center">
                <h3>{% trans 'Create Grade Fragment' %}</h3>
            </div>
            <div class="card card-outline-secondary mb-3">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>{% trans 'Semester: ' %}<span>{{ course_offering.semester.description }}</span></p>
                        <p>{% trans 'Course: ' %}<span>{{ course_offering.course }}</span></p>
                        <p>{% trans 'Coordinated: ' %}<span>{{ course_offering.coordinated }}</span>
                        </p>
                    </blockquote>
                </div>
            </div>
            <form method="post" class="form-horizontal">
                {% include 'enrollment/snippet/bootstrap_form.html' with form=form %}
                <input class="thm-btn small-btn" type="submit" value="{% trans 'Save' %}">
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker3').datetimepicker({
                format: 'YYYY-MM-DD H:mm',
		        sideBySide: true,
		        stepping: 5
            });
        });
    </script>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator/delete_grade_fragment.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="content-panel">
        <div class="cntnt-sec">
            <br>
            <div class="title-sec text-center">
                <h3>{% trans 'Delete Grade Fragment' %}</h3>
            </div>
            <div class="card card-outline-secondary mb-3">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>{% trans 'Semester: ' %}<span>{{ gradefragment.course_offering.semester.description }}</span></p>
                        <p>{% trans 'Course: ' %}<span>{{ gradefragment.course_offering.course }}</span></p>
                        <p>{% trans 'Grade Fragment Category: ' %}<span>{{ gradefragment.category }}</span></p>
                        <p>{% trans 'Grade Fragment Description: ' %}<span>{{ gradefragment.description }}</span></p>
                        <p>{% trans 'Grade Fragment weight: ' %}<span>{{ gradefragment.weight }}</span></p>
                        <q style="color:red">
                            {% trans 'Please be aware that any grades assosiated with this fragment will be deleted as well' %}
                        </q>
                    </blockquote>
                </div>
            </div>
            <form method="post">
                {% csrf_token %}
                <input class="thm-btn small-btn" type="submit" value="{% trans 'Delete' %}">
            </form>
        </div>
    </div>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator/grades_fragment_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
	<div class="content-panel">
		<div class="cntnt-sec">
			<div class="back-btn"><a href="{% url 'enrollment:home' %}">{% trans 'Go Back' %}</a></div>
			<div class="title-sec text-center">
				<h3>{% trans 'Grade Fragments' %}</h3>
			</div>
			<div class="card card-outline-secondary mb-3">
				<div class="card-block">
					<blockquote class="card-blockquote">
						<p>{% trans 'Semester: ' %}<span
								style="color:red">{{ course_offering.semester.description }}</span></p>
						<p>{% trans 'Course: ' %}<span>{{ course_offering.course }}</span></p>
						<p>{% trans 'Coordinated: ' %}<span>{{ course_offering.coordinated }}</span>
						</p>
					</blockquote>
				</div>
			</div>
			<div class="title-sec row">
				<div class="col-md-12 text-right">
					<a class="thm-btn small-btn outline-btn-dgrey float-right btn-danger"
					   href="{% url 'grade:missing_grades_report' course_offering_id=course_offering.id %}">
						<span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span> {% trans 'Missing Grades' %}
					</a>
					<a class="thm-btn small-btn" href="{% url 'grade:letter_grades' course_offering_id=course_offering.id %}">
						<span class="glyphicon glyphicon-bold" aria-hidden="true"></span><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {% trans 'Letter Grades' %}
					</a>
					<a href="{% url 'enrollment:bulk_update' course_offering_id=course_offering.id %}"
					   class="thm-btn small-btn outline-btn-dgrey float-right">
						<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> {% trans 'Bulk Update' %}
					</a>
					{% if can_create_fragment %}
						{% if fragments|length == 0 %}
							<a href="{% url 'enrollment:import_fragments' course_offering_id=course_offering.id %}"
							   title="{% trans 'Import fragments from last semester' %}"
							   class="thm-btn small-btn outline-btn-dgrey float-right" onclick="return confirm('{% trans "This will import fragments from last semester. Are you sure?" %}');">
								<span class="glyphicon glyphicon-share" aria-hidden="true"></span> {% trans 'Import Fragments' %}
							</a>
						{% endif %}
						<a href="{% url 'enrollment:create_grade_fragment_coordinator' course_offering_id=course_offering.id %}"
						   class="thm-btn small-btn outline-btn-dgrey float-right">
							<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> {% trans 'Create Grade Fragment' %}
						</a>
					{% endif %}
				</div>
				<br><br>
			</div>
			<hr>

			{% if fragments %}
				<table class="table table-condensed text-center">
					<thead>
					<tr>
						<th class="text-center">{% trans 'No.' %}</th>
						<th class="text-center">{% trans 'Category' %}</th>
						<th class="text-center">{% trans 'Description' %}</th>
						<th class="text-center">{% trans 'Type' %}</th>
						<th class="text-center">{% trans 'Weight' %}</th>
						<th class="text-center">{% trans 'Edit' %}</th>
						<th class="text-center">{% trans 'Grades' %}</th>
					</tr>
					</thead>
					<tbody>
					{% for fragment in fragments %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td>{{ fragment.category }}</td>
							<td>{{ fragment.description }}</td>
							<td>{{ fragment.get_boundary_type_display }}</td>
							<td>{{ fragment.weight }}</td>
							<td>
								<a href="{% url 'enrollment:update_grade_fragment_coordinator' course_offering_id=fragment.course_offering.id pk=fragment.id %}"
								   class="thm-btn small-btn outline-btn-dgrey">
									{% if can_create_fragment %}
										{% trans 'Edit/Delete' %}
									{% else %}
										{% trans 'Edit' %}
									{% endif %}
								</a></td>
							<td style="width: 15%">
								{% if fragment.allow_subjective_marking %}
									<div class="btn-group btn-group-justified">
										<button type="button" class="thm-btn small-btn btn-block outline-btn-dgrey dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											{% trans 'Actions' %} <span class="caret"></span>
										</button>
										<ul class="dropdown-menu">
											<li>
												<a href="{% url 'enrollment:import_grade' course_offering_id=fragment.course_offering.id grade_fragment_id=fragment.id %}">{% trans 'Import grades' %}</a>
											</li>
											<li role="separator" class="divider"></li>
											<li>
												<a href="{% url 'exam:markers' fragment.id %}">{% trans 'Subjective Marking' %}</a>
											</li>
											<li>
												<a href="{% url 'exam:settings' fragment.id %}">{% trans 'Subjective Marking (RESTART Process!)' %}</a>
											</li>
											<li>
												<a href="{% url 'exam:coordinator_markers_listing' fragment.id %}">{% trans 'Edit Marks' %}</a>
											</li>

										</ul>
									</div>
								{% else %}
									<a class="thm-btn small-btn btn-block outline-btn-dgrey dropdown-toggle" href="{% url 'enrollment:import_grade' course_offering_id=fragment.course_offering.id grade_fragment_id=fragment.id %}">{% trans 'Import grades' %}</a>
								{% endif %}
							</td>
						</tr>
					{% endfor %}
						<tr class="success">
							<td colspan="4" style="text-align: right; font-weight: bold; font-size: 120%">{% trans 'Total Weight' %}: </td>
							<td>{{ fragments_total_weight }}</td>
							<td colspan="2"></td>
						</tr>
					</tbody>
				</table>
			{% else %}
				{% trans 'There are no fragments yet' %}
			{% endif %}

		</div>
	</div>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator/update_grade_fragment.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="content-panel">
        <div class="cntnt-sec">
            <br>
            <div class="title-sec text-center">
                <h3>{% trans 'Update Grade Fragment' %}</h3>
            </div>
            <div class="card card-outline-secondary mb-3">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>{% trans 'Semester: ' %}<span>{{ gradefragment.course_offering.semester.description }}</span></p>
                        <p>{% trans 'Course: ' %}<span>{{ gradefragment.course_offering.course }}</span></p>
                        <p>{% trans 'Grade Fragment Description: ' %}<span>{{ gradefragment.description }}</span></p>
                    </blockquote>
                </div>
            </div>
            <form method="post" class="form-horizontal">
                {% include 'enrollment/snippet/bootstrap_form.html' with form=form %}
                <input class="thm-btn small-btn" type="submit" value="{% trans 'Save' %}">
                {% if can_delete_fragment %}
                    <a href="{% url 'enrollment:delete_grade_fragment_coordinator' course_offering_id=gradefragment.course_offering.id pk=gradefragment.id %}"
                       class="thm-btn small-btn outline-btn-dgrey">{% trans 'Delete' %}</a>
                {% endif %}
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker3').datetimepicker({
                format: 'YYYY-MM-DD H:mm',
		        sideBySide: true,
		        stepping: 5
            });
        });
    </script>
{% endblock %}