darajati/attendance/urls.py
from django.urls import path

from . import views

app_name = 'attendance'

urlpatterns = [
    path('section/<int:section_id>/', views.AttendanceView.as_view(),
         {'year': None, 'month': None, 'day': None}, name='section_attendance'),
    path('section/<int:section_id>/<int:year>-<int:month>-<int:day>/',
         views.AttendanceView.as_view(),
         name='section_day_attendance'),

    path('summary/<int:section_id>/<int:enrollment_id>/',
         views.StudentAttendanceSummaryView.as_view(),
         name='attendance_summary'),

    path('print/section/<int:section_id>/', views.AttendancePrintView.as_view(), name='section_attendance_print'),

    path('excuses/', views.ExcusesListingView.as_view(), name='excuses_listing'),
    path('excuse-entry/', views.ExcuseEntryView.as_view(), name='excuse_entry'),
    path('excuse-entry-confirm/<int:pk>/', views.ExcuseEntryConfirm.as_view(), name='excuse_entry_confirm'),
]

darajati/darajati/urls.py
from django.urls import re_path, include, path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = i18n_patterns(
    path('login/', views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('admin/', admin.site.urls),
    re_path(r'^impersonate/', include('impersonate.urls')),
    path('logout/', views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
)

urlpatterns += i18n_patterns(
    # Enrollment
    re_path(r'', include('enrollment.urls', namespace='enrollment')),
    re_path(r'attendance/', include('attendance.urls', namespace='attendance')),
    re_path(r'grade/', include('grade.urls', namespace='grade')),
    re_path(r'banner-integration/', include('banner_integration.urls', namespace='banner_integration')),

    # Exams
    re_path(r'exam/', include('exam.urls', namespace='exam')),
)

urlpatterns += [
    path('explorer/', include('explorer.urls')),
    path('session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

darajati/enrollment/urls.py
from django.urls import re_path
from django.views.generic import TemplateView

from . import views

app_name = 'enrollment'

# Instructor
urlpatterns = [
    re_path(r'^$', views.HomeView.as_view(), name='home'),
    re_path(r'^instructor/$', views.InstructorView.as_view(), name='instructor'),
    re_path(r'^student/section/(?P<section_id>[0-9]+)/$', views.SectionStudentView.as_view(),
        name='section_students'),
]

# Coordinator
urlpatterns += [
    re_path(r'^coordinator/$', views.CoordinatorView.as_view(), name='coordinator'),
    re_path(r'^coordinator/course/(?P<course_offering_id>[0-9]+)/$', views.CoordinatorSectionView.as_view(),
            name='course_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/$',
            views.CoordinatorGradeFragmentView.as_view(),
            name='grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/import-fragments/$',
            views.ImportGradeFragmentsView.as_view(), name='import_fragments'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/bulk-update/$',
            views.BulkUpdateGradeFragmentsView.as_view(), name='bulk_update'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/edit/(?P<pk>[0-9]+)/$',
            views.CoordinatorEditGradeFragmentView.as_view(),
            name='update_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/delete/(?P<pk>[0-9]+)/$',
            views.CoordinatorDeleteGradeFragmentView.as_view(),
            name='delete_grade_fragment_coordinator'),
    re_path(r'^coordinator/grade-fragment/(?P<course_offering_id>[0-9]+)/create/$',
            views.CoordinatorCreateGradeFragmentView.as_view(),
            name='create_grade_fragment_coordinator'),
    re_path(r'^coordinator/section/(?P<section_id>[0-9]+)/$', views.CoordinatorView.as_view(),
            name='section_coordinator'),
    re_path(r'^coordinator/grades/(?P<course_offering_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/import-grade/$',
            views.ImportGradesView.as_view(), name='import_grade'),
]

# Admin
urlpatterns += [
    re_path(r'^controls/$', views.AdminControlsView.as_view(), name='controls'),
]

# Others
urlpatterns += [
    re_path(r'^unauthorized/$', TemplateView.as_view(template_name='unauthorized.html'), name='unauthorized'),
]

darajati/exam/urls.py
from django.urls import re_path

from . import views

app_name = 'exam'

urlpatterns = [
    re_path(r'^rooms/$',
            views.RoomListView.as_view(),
            name='list_rooms'
            ),

    re_path(r'^rooms/add/$',
            views.RoomAddView.as_view(),
            name='add_room'
            ),

    re_path(r'^rooms/(?P<room_id>[0-9]+)/edit/$',
            views.RoomEditView.as_view(),
            name='edit_room'
            ),

    re_path(r'^settings/(?P<fragment_id>[0-9]+)/$',
            views.ExamSettingsView.as_view(),
            name='settings'
            ),

    re_path(r'^shifts/(?P<fragment_id>[0-9]+)/$',
            views.ExamShiftsView.as_view(),
            name='shifts'
            ),

    re_path(r'^rooms/(?P<fragment_id>[0-9]+)/$',
            views.ExamRoomsView.as_view(),
            name='exam_rooms'
            ),

    re_path(r'^markers/(?P<fragment_id>[0-9]+)/$',
            views.MarkersView.as_view(),
            name='markers'
            ),

    re_path(r'^marks/(?P<marker_id>[0-9]+)/$',
            views.StudentMarksView.as_view(),
            name='marks'
            ),

    re_path(r'^unaccepted/(?P<fragment_id>[0-9]+)/$',
            views.UnacceptedStudentMarksView.as_view(),
            name='unaccepted_markers'
            ),

    re_path(r'^markers-listing/(?P<fragment_id>[0-9]+)/$',
            views.CoordinatorMarkersListing.as_view(),
            name='coordinator_markers_listing'
            ),
]

darajati/grade/urls.py
from . import views
from django.urls import re_path, path

app_name = 'grade'

urlpatterns = [
    re_path(r'^section/(?P<section_id>[0-9]+)/$',
            views.GradeFragmentView.as_view(),
            name='section_grade'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/$',
            views.GradesView.as_view(),
            name='plan_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/(?P<grade_fragment_id>[0-9]+)/view/$',
            views.DisplayGradesView.as_view(),
            name='view_grades'),

    re_path(r'^section/(?P<section_id>[0-9]+)/create-grade-plan/$',
            views.CreateGradeFragmentView.as_view(),
            name='create_grade_fragment'),

    re_path(r'^section/(?P<section_id>[0-9]+)/grades-report/$',
            views.GradeReportView.as_view(),
            name='section_grade_report'),

    re_path(r'^letter-grades/(?P<course_offering_id>[0-9]+)/$',
            views.LetterGradesView.as_view(), name='letter_grades'),

    path('letter-grades-promotion/<int:course_offering_id>/', views.LetterGradesPromotionView.as_view(),
         name='letter_grades_promotion'),

    path('letter-grades/<int:course_offering_id>/import/', views.ImportLetterGradesView.as_view(),
         name='letter_grades_import'),

    path('missing-grades-report/<int:course_offering_id>/', views.MissingGradesReportView.as_view(),
         name='missing_grades_report'),
]

darajati/enrollment/views.py
from django.contrib import messages
from django.db.models import F, Sum
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, ListView, UpdateView, CreateView, FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.base import ContextMixin
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from extra_views import ModelFormSetView

from .models import Section, Enrollment, Coordinator, CourseOffering, Instructor
from .tasks import get_students_enrollment_grades
from .forms import GradesImportForm
from .utils import now
from exam.models import Marker

from grade.forms import GradeFragmentForm, GradeFragmentsFormSet, BulkGradeFragmentForm

from grade.models import GradeFragment, StudentGrade


class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        if Instructor.is_active_instructor(self.request.user):
            if Instructor.is_active_coordinator(self.request.user.instructor):
                return redirect('enrollment:coordinator')
            return redirect('enrollment:instructor')
        else:
            return redirect('enrollment:unauthorized')


class InstructorBaseView(LoginRequiredMixin, UserPassesTestMixin, ContextMixin):
    """
    :InstructorBaseView:
    - check if the current user is instructor or superuser
    - redirect the current user even if he is AnonymousUser
    """
    # TODO: add a check for the active user

    section_id = None
    section = None
    coordinator = None

    def dispatch(self, request, *args, **kwargs):
        """
         Assign section_id and get section object
        """
        if request.user.is_authenticated:
            if self.kwargs.get('section_id'):
                self.section_id = self.kwargs['section_id']
                self.section = Section.get_section(self.section_id)
            if Instructor.is_active_coordinator(self.request.user.instructor):
                self.coordinator = self.request.user.instructor.coordinators
        return super(InstructorBaseView, self).dispatch(request, *args, **kwargs)

    def test_func(self, **kwargs):
        is_instructor_section = self.section.is_instructor_section(self.request.user.instructor)
        is_coordinator = self.section.is_coordinator_section(self.request.user.instructor)

        if is_instructor_section or is_coordinator:
            return True
        messages.error(self.request,
                       _('The requested section do not belong to you, or it is out of this semester'))
        return False

    def get_context_data(self, **kwargs):
        context = super(InstructorBaseView, self).get_context_data(**kwargs)
        context['section'] = self.section
        context['section_id'] = self.section_id
        context['coordinator'] = self.coordinator
        return context

    def get_login_url(self):
        """
        
        :return: 
        """
        if self.request.user.is_authenticated:
            return reverse_lazy('enrollment:home')


class InstructorView(InstructorBaseView, ListView):
    template_name = 'enrollment/sections_list.html'
    model = Section
    ordering = 'code'
    context_object_name = 'sections'

    def test_func(self, **kwargs):
        return True if Instructor.is_active_instructor(self.request.user) else False

    def get_context_data(self, **kwargs):
        context = super(InstructorView, self).get_context_data(**kwargs)

        context['active_marking_assignments'] = Marker.objects.filter(
            instructor__user=self.request.user,
            exam_room__exam_shift__settings__fragment__entry_start_date__lte=now(),
            exam_room__exam_shift__settings__fragment__entry_end_date__gte=now(),
            order__lte=F('exam_room__exam_shift__settings__number_of_markers'),
        )

        context['tie_breaking_assignments'] = Marker.objects.filter(
            instructor__user=self.request.user,
            exam_room__exam_shift__settings__fragment__entry_start_date__lte=now(),
            exam_room__exam_shift__settings__fragment__entry_end_date__gte=now(),
            order__gt=F('exam_room__exam_shift__settings__number_of_markers'),
        ).first()

        return context

    def get_queryset(self):
        return Section.get_instructor_sections(self.request.user.instructor)


class SectionStudentView(InstructorBaseView, ListView):
    template_name = 'enrollment/instructor/section_students.html'
    model = Enrollment
    context_object_name = 'enrollments'

    def get_queryset(self):
        query = Enrollment.get_students_of_section(self.section_id)
        return query


# Coordinator views
class CoordinatorBaseView(LoginRequiredMixin, UserPassesTestMixin, ContextMixin):
    coordinator = None
    course_offering_id = None
    course_offering = None
    __attributes_initiated = False

    def init_class_attributes(self, request, *args, **kwargs):
        if self.__attributes_initiated:
            return

        if request.user.is_authenticated:
            if Coordinator.objects.filter(instructor=request.user.instructor).exists():
                self.coordinator = request.user

    def dispatch(self, request, *args, **kwargs):
        self.init_class_attributes(request, *args, **kwargs)
        return super(CoordinatorBaseView, self).dispatch(request, *args, **kwargs)

    def test_func(self):
        if not self.coordinator:
            messages.error(self.request,
                           _('You can not access this page'))
            return False
        return True

    def get_context_data(self, **kwargs):
        context = super(CoordinatorBaseView, self).get_context_data(**kwargs)
        context['coordinator'] = self.coordinator
        return context

    def get_login_url(self):
        if self.request.user != "AnonymousUser":
            return reverse_lazy('enrollment:home')
        return super(CoordinatorBaseView, self).get_login_url()


class CoordinatorEditBaseView(CoordinatorBaseView):

    def init_class_attributes(self, request, *args, **kwargs):
        super().init_class_attributes(request, *args, **kwargs)
        self.course_offering_id = self.kwargs['course_offering_id']
        self.course_offering = get_object_or_404(CourseOffering, pk=self.course_offering_id)

    def test_func(self):
        rules = super(CoordinatorEditBaseView, self).test_func()
        if rules:
            if not Coordinator.is_coordinator_of_course_offering_in_this_semester(
                    self.request.user.instructor,
                    self.course_offering):
                messages.error(self.request, _('You can not access this page'))
                return False

            return True
        return False


class CoordinatorView(CoordinatorBaseView, ListView):
    template_name = 'enrollment/coordinator/courses_list.html'
    model = Coordinator
    context_object_name = 'courses'

    def get_queryset(self):
        return Coordinator.objects.filter(instructor=self.coordinator.instructor,
                                          course_offering__in=CourseOffering.get_active_course_offerings())


class CoordinatorSectionView(CoordinatorEditBaseView, ListView):
    template_name = 'enrollment/sections_list.html'
    model = Section
    ordering = 'code'
    context_object_name = 'sections'

    def get_queryset(self):
        queryset = super(CoordinatorSectionView, self).get_queryset()
        return queryset.filter(course_offering=self.course_offering).exclude(
            scheduled_periods__isnull=True
        )


class CoordinatorGradeFragmentView(CoordinatorEditBaseView, ListView):
    template_name = 'enrollment/coordinator/grades_fragment_list.html'
    model = GradeFragment
    context_object_name = 'fragments'

    def get_queryset(self):
        queryset = super(CoordinatorGradeFragmentView, self).get_queryset()
        return queryset.filter(course_offering=self.course_offering)

    def get_context_data(self, **kwargs):
        context = super(CoordinatorGradeFragmentView, self).get_context_data(**kwargs)
        context['course_offering'] = self.course_offering
        context['can_create_fragment'] = self.course_offering.semester.can_create_grade_fragment()
        context['fragments_total_weight'] = self.get_queryset().aggregate(Sum('weight')).get('weight__sum')
        return context


class ImportGradeFragmentsView(CoordinatorEditBaseView, View):

    def test_func(self):
        rules = super(ImportGradeFragmentsView, self).test_func()
        if rules:
            if not self.course_offering.semester.can_create_grade_fragment():
                messages.error(self.request, _('The deadline to add grade fragments is over'))
                return False

            if self.course_offering.grade_fragments.count() > 0:
                messages.error(self.request, _('You can NOT import fragments from previous semester when you already '
                                               'have created fragments in this semester'))
                return False
            return True
        return False

    def get(self, request, *args, **kwargs):
        self.init_class_attributes(request, *args, **kwargs)

        latest_course_offering = CourseOffering.objects.filter(
            course=self.course_offering.course,
        ).order_by('-semester__end_date').exclude(pk=self.course_offering_id).first()

        if latest_course_offering and len(latest_course_offering.grade_fragments.all()):
            for fragment in latest_course_offering.grade_fragments.all():
                fragment.pk = None
                fragment.course_offering = self.course_offering
                fragment.entry_start_date = self.course_offering.semester.start_date
                fragment.entry_end_date = self.course_offering.semester.start_date
                fragment.save()

darajati/enrollment/templates/enrollment/admin_controls.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="content-panel">
    <div class="cntnt-sec">
        <div class="title-sec text-center">
            <h3>{% trans 'Admin Controls' %}</h3>
            <form method="post">
                {% csrf_token %}
                <input class="thm-btn small-btn save-btn" type="submit" name="create_grade" value="{% trans 'Create Grades' %}">

            </form>
        </div>
    </div>
</div>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator_course_sections_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="content-panel">
    <div class="cntnt-sec">
        <div class="title-sec text-center">
            <h3>{% trans 'Find your current enrolled sections' %}</h3>
        </div>
        <br>
        {% if sections %}
        <table class="table table-condensed text-center">
            <thead>
            <tr>
                <th class="text-center">{% trans 'Semester Code' %}</th>
                <th class="text-center">{% trans 'Course Code' %}</th>
                <th class="text-center">{% trans 'Course Name' %}</th>
                <th class="text-center">{% trans 'Section Code' %}</th>
                <th class="text-center">{% trans 'Attendances' %}</th>
                <th class="text-center">{% trans 'Grades' %}</th>
                <th class="text-center">{% trans 'Students' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for section in sections %}
                <tr>
                    <td>{{ section.course_offering.semester.code }}</td>
                    <td {% if section.course_offering.coordinated %} style="color:red" {% endif %}>
                        {{ section.course_offering.course.code }}</td>
                    <td>{{ section.course_offering.course.name }}</td>
                    <td>{{ section.code }}</td>
                    <td><a href="{% url 'attendance:section_attendance' section_id=section.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'View/Edit' %}</a></td>
                    <td><a href="{% url 'grade:section_grade' section_id=section.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'View/Edit' %}</a></td>
                    <td><a href="{% url 'enrollment:section_students' section_id=section.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'View' %}</a></td>
                    <td></td>
                </tr>
             {% endfor %}
            </tbody>
        </table>
        {% else %}
                {% trans 'There are no results' %}
        {% endif %}

    </div>
</div>
{% endblock %}

darajati/enrollment/templates/enrollment/coordinator_courses_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="content-panel">
    <div class="cntnt-sec">
        <div class="title-sec text-center">
            <h3>{% trans 'Find your current coordinated courses' %}</h3>
        </div>
        <br>
        {% if courses %}
        <table class="table table-condensed text-center">
            <thead>
            <tr>
                <th class="text-center">{% trans 'Semester Code' %}</th>
                <th class="text-center">{% trans 'Course Code' %}</th>
                <th class="text-center">{% trans 'Course Name' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_offering.semester.code }}</td>
                    <td {% if course.course_offering.coordinated %} style="color:red" {% endif %}>
                        {{ course.course_offering.course.code }}</td>
                    <td>{{ course.course_offering.course.name }}</td>
                    <td><a href="{% url 'enrollment:course_coordinator' course_offering_id=course.course_offering.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'Edit/Access' %}</a></td>
                </tr>
             {% endfor %}
            </tbody>
        </table>
        {% else %}
                {% trans 'There are no results' %}
        {% endif %}

    </div>
</div>
{% endblock %}

darajati/enrollment/templates/enrollment/sections_list.html
{% extends "base.html" %}

{% load i18n %}
{% load humanize %}

{% block content %}
	<div class="content-panel">
		<div class="cntnt-sec">
			<div class="back-btn"><a href="{% url 'enrollment:home' %}">{% trans 'Go Back' %}</a></div>
			<div class="title-sec text-center">
				<h3>{% trans 'Find your current enrolled sections' %}</h3>
			</div>
			<hr>
			{% if sections %}
				<table class="table table-condensed text-center">
					<thead>
					<tr>
						<th class="text-center">{% trans 'Semester Code' %}</th>
						<th class="text-center">{% trans 'Course Code' %}</th>
						<th class="text-center">{% trans 'Section Code' %}</th>
						<th class="text-center">{% trans 'Being Taught By' %}</th>
						<th class="text-center">{% trans 'Attendances' %}</th>
						<th class="text-center">{% trans 'Grades' %}</th>
						<th class="text-center">{% trans 'Students' %}</th>
						<th></th>
					</tr>
					</thead>
					<tbody>
					{% for section in sections %}
						<tr>
							<td>{{ section.course_offering.semester.code }}</td>
							<td {% if section.course_offering.coordinated %} style="color:red" {% endif %}>
								{{ section.course_offering.course.code }}</td>
							<td>{{ section.code }}</td>
							<td>{{ section.teachers }}</td>
							<td>
								<a href="{% url 'attendance:section_attendance' section_id=section.id %}" class="thm-btn small-btn outline-btn-dgrey">{% trans 'Enter' %}</a>&nbsp;&nbsp;<a target="_blank" href="{% url 'attendance:section_attendance_print' section_id=section.id %}"
								                                                                                                                                                                class="thm-btn small-btn outline-btn-dgrey"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> {% trans 'Sheet' %}</a>
							</td>
							<td><a href="{% url 'grade:section_grade' section_id=section.id %}"
							       class="thm-btn small-btn outline-btn-dgrey">{% trans 'View/Edit' %}</a>&nbsp;<a href="{% url 'grade:section_grade_report' section_id=section.id %}"
							       class="thm-btn small-btn outline-btn-dgrey"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> {% trans 'Report' %}</a></td>
							<td><a href="{% url 'enrollment:section_students' section_id=section.id %}"
							       class="thm-btn small-btn outline-btn-dgrey">{% trans 'View' %}</a></td>
							<td></td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			{% else %}
				{% trans 'There are no results' %}
			{% endif %}

			{% if active_marking_assignments %}
				<br><br>
				<div class="title-sec text-center">
					<h3>{% trans 'Marking Assignments' %}</h3>
				</div>
				<hr>
				<table class="table table-condensed text-center">
					<thead>
					<tr>
						<th class="text-center">{% trans 'Semester Code' %}</th>
						<th class="text-center">{% trans 'Course Code' %}</th>
						<th class="text-center">{% trans 'Course Name' %}</th>
						<th class="text-center">{% trans 'Fragment' %}</th>
						<th class="text-center">{% trans 'Exam Room' %}</th>
						<th class="text-center">{% trans 'Order' %}</th>
						<th class="text-center"></th>
						<th></th>
					</tr>
					</thead>
					<tbody>
					{% for marker in active_marking_assignments %}
						<tr>
							<td>{{ marker.exam_room.exam_shift.settings.fragment.course_offering.semester.code }}</td>
							<td
									{% if marker.exam_room.exam_shift.settings.fragment.course_offering.coordinated %} style="color:red" {% endif %}>
								{{ marker.exam_room.exam_shift.settings.fragment.course_offering.course.code }}</td>
							<td>{{ marker.exam_room.exam_shift.settings.fragment.course_offering.course.name }}</td>
							<td>{{ marker.exam_room.exam_shift.settings.fragment.short_name }}</td>
							<td>{{ marker.exam_room }}</td>
							<td>{{ marker.order|ordinal }}</td>
							<td><a href="{% url 'exam:marks' marker.pk %}"
							       class="thm-btn small-btn outline-btn-dgrey">{% trans 'Enter Marks' %}</a></td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			{% endif %}
			{% if tie_breaking_assignments %}
				<center>
					<a href="{% url 'exam:marks' tie_breaking_assignments.pk %}"
							       class="thm-btn small-btn outline-btn-dgrey">{% trans 'Enter Marks For Tie-breaking' %}</a>
				</center>
			{% endif %}
		</div>
	</div>
{% endblock %}